# -*- coding: utf-8 -*-
"""comparinglabelsandnltk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UjngrcgIwhwP6Ex8KIJkHt8JXkPjzLQ
"""

from google.colab import files

nltk = files.upload()

regularmodel = files.upload()

#making the dataframe
import io
import pandas as pd
nltk_data = pd.read_csv(io.BytesIO(nltk['nltkmodel.csv']))
regular_data = pd.read_csv(io.BytesIO(regularmodel['countries_headlines-2 - Sheet1.csv']))

#jaccard score
matching_values = sum(1 for val1, val2 in zip(nltk_data['label'], regular_data['label']) if val1 == val2)
total_values = len(nltk_data['label'])
accuracy = (matching_values / total_values) * 100
print(accuracy)