# -*- coding: utf-8 -*-
"""ComparingLabelsandLogreg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166qs0PFQ-VW0VUI7orMr4xA4FzZhwj2Q
"""

from google.colab import files

logreg = files.upload()

regularmodel = files.upload()

import io
import pandas as pd
logreg_data = pd.read_csv(io.BytesIO(logreg['logreg_data (1).csv']))
regular_data = pd.read_csv(io.BytesIO(regularmodel['countries_headlines-2 - Sheet1.csv']))

#jaccard score
matching_values = sum(1 for val1, val2 in zip(logreg_data['label'], regular_data['label']) if val1 == val2)
total_values = len(logreg_data['label'])
accuracy = (matching_values / total_values) * 100
print(accuracy)