# -*- coding: utf-8 -*-
"""nltk model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xde4eUHzfehb4SSc4g2wxmwOEWEqDyAy
"""

from google.colab import files

uploaded = files.upload()

#making the dataframe
import io
import pandas as pd

headlines_data = pd.read_csv(io.BytesIO(uploaded['realcountriesdata.csv']))

import nltk
nltk.download("vader_lexicon")
from nltk.sentiment.vader import SentimentIntensityAnalyzer as SIA

sia = SIA()
results = []

for sentence in headlines_data['headline_text']:
  polarity_scores = sia.polarity_scores(sentence)
  if polarity_scores['compound'] > 0.2:
    results.append(1)
  elif(polarity_scores['compound']< -0.2):
    results.append(-1)
  else:
    results.append(0)

headlines_data['label'] = results

headlines_data = headlines_data[:-600]
headlines_data

nltk_data = headlines_data
nltk_data.to_csv('nltkmodel.csv',index = False)
files.download('nltkmodel.csv')